@startuml
!pragma layout smetana

Class User {
- int id
- String username
- String password
- String email
- String phoneNumber
- boolean isAdmin

}

Class Order {
- int id
- int price
- ArrayList <Part> partList
}

Class Part {
- int id
- int amount
- int length
- int unit
}

User --* Order
Order --* Part

@enduml